In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
cancer = load_breast_cancer()
df = pd.DataFrame(cancer.data,columns=cancer.feature_names)

In [3]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness   
0          17.99         10.38          122.80     1001.0          0.11840  \
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry   
0             0.27760         0.30010              0.14710         0.2419  \
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture   
0                   0.07871  ...        25.380          17.33  \
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness   
0             184.60      2019.0           0.16220            0.66560  \
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry   
0             0.7119                0.2654          0.4601  \
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [5]:
X = df
Y = pd.Series(cancer.target)

In [6]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Length: 569, dtype: int32

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 40)

In [9]:
# KNN Model
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)
knn_predictions = knn.predict(X_test)

In [11]:
accuracy = accuracy_score(Y_test, knn_predictions)
print(f'Accuracy of the KNN Model: {accuracy * 100:.2f}%')

Accuracy of the KNN Model: 93.86%


In [12]:
print("Confusion Matrix of the KNN Model:\n")
print(confusion_matrix(Y_test, knn_predictions))

Confusion Matrix of the KNN Model:

[[35  4]
 [ 3 72]]


In [13]:
print("Classification Report for KNN Model:\n")
print(classification_report(Y_test, knn_predictions))

Classification Report for KNN Model:

              precision    recall  f1-score   support

           0       0.92      0.90      0.91        39
           1       0.95      0.96      0.95        75

    accuracy                           0.94       114
   macro avg       0.93      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114



In [14]:
# SVM Model
from sklearn.svm import SVC

svm = SVC(kernel='linear', C=1)
svm.fit(X_train, Y_train)
svm_predictions = svm.predict(X_test)

In [15]:
accuracy = accuracy_score(Y_test, svm_predictions)
print(f'Accuracy of the SVM Model: {accuracy * 100:.2f}%')

Accuracy of the SVM Model: 94.74%


In [16]:
print("Confusion Matrix of the SVM Model:\n")
print(confusion_matrix(Y_test, svm_predictions))

Confusion Matrix of the SVM Model:

[[37  2]
 [ 4 71]]


In [17]:
print("Classification Report for SVM Model:\n")
print(classification_report(Y_test, svm_predictions))

Classification Report for SVM Model:

              precision    recall  f1-score   support

           0       0.90      0.95      0.92        39
           1       0.97      0.95      0.96        75

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.94       114
weighted avg       0.95      0.95      0.95       114



In [18]:
# Ensemble Model
from scipy.stats import mode

combined_predictions = np.vstack((knn_predictions, svm_predictions)).T
ensemble_predictions, _ = mode(combined_predictions, axis=1, keepdims=True)

In [19]:
accuracy = accuracy_score(Y_test, ensemble_predictions)
conf_matrix = confusion_matrix(Y_test, ensemble_predictions)
class_report = classification_report(Y_test, ensemble_predictions)

print(f'Ensemble Accuracy: {accuracy*100:.2f}%')
print("\n\nEnsemble Confusion Matrix:\n")
print(conf_matrix)
print("\n\nEnsemble Classification Report:\n")
print(class_report)

Ensemble Accuracy: 92.98%


Ensemble Confusion Matrix:

[[37  2]
 [ 6 69]]


Ensemble Classification Report:

              precision    recall  f1-score   support

           0       0.86      0.95      0.90        39
           1       0.97      0.92      0.95        75

    accuracy                           0.93       114
   macro avg       0.92      0.93      0.92       114
weighted avg       0.93      0.93      0.93       114

